stages:
  - build
  - test

variables:
  COVERAGE_DIR: "_coverage"
  TSONNET_DOCKER_IMAGE: $CI_REGISTRY_IMAGE:latest

build-docker-image-job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $TSONNET_DOCKER_IMAGE || true
    - docker build --cache-from $TSONNET_DOCKER_IMAGE -t $TSONNET_DOCKER_IMAGE .
    - docker push $TSONNET_DOCKER_IMAGE

build-job:
  image: $TSONNET_DOCKER_IMAGE
  stage: build
  needs:
    - build-docker-image-job
  script:
    - make build

test-job:
  image: $TSONNET_DOCKER_IMAGE
  stage: test
  needs:
    - build-docker-image-job
  script:
    - make test

coverage-job:
  image: $TSONNET_DOCKER_IMAGE
  stage: test
  needs:
    - test-job
  script:
    - make coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: "${COVERAGE_DIR}/cobertura.xml"
